### ISSUE TITLE
midis2jam2 not opening macos monterey

### ISSUE THREAD

**Issue by ijnfuso** [wyskoj/midis2jam2#229] opened 2024-12-19 23:02 UTC
just installed midi2jam2 and it doesn't want to open on my system...
i'm running macos monterey on a 21,5 inch imac
the program tries to load (the icon bounces on the dock for long) however it never opens and remains non responsive
![Schermata 2024-12-20 alle 00 01 12](https://github.com/user-attachments/assets/6f65dd4b-3cf6-4d5a-a467-536d133f6506)
above a screenshot of my mac specs

**Comment by wyskoj** [comment] 2024-12-20 02:43
This is a known issue and a fix is in the works. Thanks for letting me know!

Duplicate of #203.

**Closed by wyskoj** 2024-12-20 02:43 UTC
Labels: bug
