### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by ASHE45335** [wyskoj/midis2jam2#183] opened 2024-03-31 04:11 UTC
**Describe the bug**
When I start midis2jam2, I get this error message:

An error has occurred during startup:
java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at org.wysko.midis2jam2.gui.viewmodel.HomeViewModel.applyConfiguration(HomeViewModel.kt:145)
	at org.wysko.midis2jam2.gui.viewmodel.HomeViewModel.<init>(HomeViewModel.kt:125)
	at org.wysko.midis2jam2.gui.viewmodel.HomeViewModel$Companion.create(HomeViewModel.kt:135)
	at org.wysko.midis2jam2.gui.viewmodel.HomeViewModel$Companion.create$default(HomeViewModel.kt:131)
	at org.wysko.midis2jam2.MainKt.main(Main.kt:67)
	at org.wysko.midis2jam2.MainKt$main$6.invoke(Main.kt)
	at org.wysko.midis2jam2.MainKt$main$6.invoke(Main.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:270)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at org.wysko.midis2jam2.MainKt.main(Main.kt)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

**Offending MIDI file**
No midi file used

**System**
Windows 10
![Uploading error.PNG…]()

**Comment by orangeisbetter** [comment] 2024-04-04 13:41
I had the same problem. The reason it happened for me was when I had previously selected a MIDI output device that was no longer connected when I started the app. The solution for me was to reconnect that device and then start the program. Should be a simple fix.

**Comment by wyskoj** [comment] 2024-04-04 23:23
Duplicate of #180. Will be fixed in next version.

The temporary fix is to reconnect the device, or clear the software configuration by deleting the files in the `.midis2jam2` folder, located within your user folder.

**Closed by wyskoj** 2024-04-04 23:23 UTC
Labels: bug
