### ISSUE TITLE
Settings/preferences not saving

### ISSUE THREAD

**Issue by cactus410** [wyskoj/midis2jam2#184] opened 2024-05-09 22:50 UTC
**Describe the bug**
All settings and soundfonts do not save, reverting back to default (in the case of the soundfont menu, it uses some soundfonts i had, so it must've saved at one point, see below) even in administrator mode.

**Offending MIDI file**
N/A

**Expected behavior**
it's expected for the settings to save, and the soundfonts to also save.

**Screenshots**
![image](https://github.com/wyskoj/midis2jam2/assets/54778135/bf30244d-25ce-4644-9f4a-3b0baaface10)

**System**
Windows 10 Pro 64-bit (build 19045)
Intel Core i7-9700 CPU @ 3.00GHz
AMD Radeon RX-550

**Additional context**
Changing permissions to "Full Control" and, as i said, executing in administrator mode didn't work.

(The error and output log files just in case it matters)
[error.log](https://github.com/wyskoj/midis2jam2/files/15268456/error.log)
[output.log](https://github.com/wyskoj/midis2jam2/files/15268457/output.log)

**Comment by jonahh2160** [comment] 2024-05-13 20:56
I'm also having this issue

**Comment by wyskoj** [comment] 2024-05-14 00:55
@cactus410 @jonahh2160 Change some settings, then look in the `.midis2jam2` folder within your Windows user folder. Do the .json files reflect the settings you just set (or are they even there at all)?

**Comment by cactus410** [comment] 2024-05-14 22:01
@wyskoj The folder is there + settings and other stuff, but they don't change, i've modified the permissions of the folder - nothing, modified the .json file - nothing, "fullscreen" just reverts to true once the program starts

**Comment by wyskoj** [comment] 2024-05-14 22:37
@cactus410 Change a setting, immediately close the program, then upload the error and output logs without restarting midis2jam2.

**Comment by cactus410** [comment] 2024-05-15 00:29
[error.log](https://github.com/wyskoj/midis2jam2/files/15314871/error.log)
[output.log](https://github.com/wyskoj/midis2jam2/files/15314872/output.log)
Done. (Changed setting was fullscreen to false.)

**Comment by wyskoj** [comment] 2024-06-21 19:29
@cactus410 Sorry for the longer-than-a-month delay! This issue stumps me since I have no way of preproducing it. Could you try manually editing any of the .json configuration files and see if the change is reflected in the program? (Edit the file while midis2jam2 is closed, then open it.)

**Comment by wyskoj** [comment] 2024-07-10 12:54
Closing until further information is supplied.

**Closed by wyskoj** 2024-07-10 12:54 UTC
Labels: bug

**Comment by cactus410** [comment] 2024-07-13 15:16
Hello, i'm SUPER sorry for the radio silence, but just uninstalling and reinstalling m2j2 worked, soundbanks and settings save too.

**Comment by wyskoj** [comment] 2024-07-13 23:00
Okay, great!
