### ISSUE TITLE
Add video output functionality

### ISSUE THREAD

**Issue by src3453** [wyskoj/midis2jam2#159] opened 2022-12-30 12:50 UTC
**Is your feature request related to a problem? Please describe.**
I always use a screen recorder to take videos. The ability to output videos directly without a UI would be more useful.

**Describe the solution you'd like**
Add video output functionality using FFMpeg, etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by wyskoj** [comment] 2022-12-30 16:18
Duplicate of #100.

**Closed** 2022-12-30 16:19 UTC
Labels: enhancement
