### ISSUE TITLE
Option to render video with no lag using ffmpeg

### ISSUE THREAD

**Issue by frog8412** [wyskoj/midis2jam2#188] opened 2024-06-27 09:34 UTC
If you have ever used Ultralight MIDI Player made by PipiraMine, there's an option to render midi as video with audio and no lag. This works with ffmpeg, and so i want to see this kind of feature in midis2jam2, since some devices are struggling when playing in real time.

**Comment by wyskoj** [comment] 2024-06-27 11:50
This has been on my backlog for quite some time, and I need to get around and implement this. Duplicate of #100. Thanks for your feedback!

**Closed** 2024-06-27 11:50 UTC
Labels: enhancement
