### ISSUE TITLE
(v1.6.0) Visualizer only renders in top left corner of window no matter what resolution is chosen

### ISSUE THREAD

**Issue by kyfreed** [wyskoj/midis2jam2#133] opened 2022-07-31 17:17 UTC
I have tried a number of different resolutions, even the minimum, and the visualizer only uses a fraction of the window.
<img width="1280" alt="Screenshot 2022-07-31 100636" src="https://user-images.githubusercontent.com/8462295/182037943-7d19a2b4-a584-481e-8e55-d71e6b01c716.png">

**Comment by wyskoj** [comment] 2022-07-31 17:55
I believe this is a duplicate of #120. @kyfreed Is your issue resolved if you set your Windows monitor scale to 100%?

**Comment by wyskoj** [comment] 2022-08-12 21:41
Closing until further information provided.

**Closed by wyskoj** 2022-08-12 21:41 UTC
Labels: bug
